// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using GraphQLserver.Middleware;
using GraphQLserver.Services;

namespace GraphQLserver.Models;

public partial class BMProjekt2024Context
{

  private readonly int? _tenantId;


  public BMProjekt2024Context(DbContextOptions<BMProjekt2024Context> options, 
      [Service] ITenantIdResolverService tenantidresolver)
      : base(options)
  {
    _tenantId = tenantidresolver.TenantId;
  }

  partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
  {


    modelBuilder.Entity<Customer>(entity =>
    {
      entity.HasQueryFilter(c => c.VenueId == _tenantId);
    });

    modelBuilder.Entity<EventSection>(entity =>
    {
      entity.HasQueryFilter(c => c.VenueId == _tenantId);
    });

    modelBuilder.Entity<Event>(entity =>
    {
      entity.HasQueryFilter(c => c.VenueId == _tenantId);
    });

    modelBuilder.Entity<Section>(entity =>
    {
      entity.HasQueryFilter(c => c.VenueId == _tenantId);
    });

    modelBuilder.Entity<TicketPurchase>(entity =>
    {
      entity.HasQueryFilter(c => c.VenueId == _tenantId);
    });

    modelBuilder.Entity<Ticket>(entity =>
    {
      entity.HasQueryFilter(c => c.VenueId == _tenantId);
    });

    modelBuilder.Entity<Venue>(entity =>
    {
      entity.HasQueryFilter(v => v.VenueId == _tenantId);
    });
  }
}