// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraphQLserver.Models;

public partial class Customer
{
    public int VenueId { get; set; }

    public int CustomerId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string PostalCode { get; set; }

    public string CountryCode { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Country CountryCodeNavigation { get; set; }

    public virtual ICollection<TicketPurchase> TicketPurchases { get; set; } = new List<TicketPurchase>();

    public virtual Venue Venue { get; set; }
}