// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraphQLserver.Models;

public partial class Event
{
    public int VenueId { get; set; }

    public int EventId { get; set; }

    public string EventName { get; set; }

    public string Subtitle { get; set; }

    public DateTime Date { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<EventSection> EventSections { get; set; } = new List<EventSection>();

    public virtual Venue Venue { get; set; }
}