// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraphQLserver.Models;

public partial class EventSection
{
    public int VenueId { get; set; }

    public int EventId { get; set; }

    public int SectionId { get; set; }

    public decimal Price { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Event Event { get; set; }

    public virtual Section Section { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}