// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraphQLserver.Models;

public partial class LastExtracted
{
    public byte[] LastExtractedVenueRowVersion { get; set; }

    public byte[] LastExtractedEventRowVersion { get; set; }

    public byte[] LastExtractedTicketRowVersion { get; set; }

    public string Lock { get; set; }
}