// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraphQLserver.Models;

public partial class Section
{
    public int VenueId { get; set; }

    public int SectionId { get; set; }

    public string SectionName { get; set; }

    public short SeatRows { get; set; }

    public short SeatsPerRow { get; set; }

    public decimal StandardPrice { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<EventSection> EventSections { get; set; } = new List<EventSection>();

    public virtual Venue Venue { get; set; }
}