// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraphQLserver.Models;

public partial class TicketPurchase
{
    public int VenueId { get; set; }

    public int TicketPurchaseId { get; set; }

    public DateTime PurchaseDate { get; set; }

    public decimal PurchaseTotal { get; set; }

    public int CustomerId { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Customer Customers { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}