// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraphQLserver.Models;

public partial class Ticket
{
    public int VenueId { get; set; }

    public int TicketId { get; set; }

    public int RowNumber { get; set; }

    public int SeatNumber { get; set; }

    public int EventId { get; set; }

    public int SectionId { get; set; }

    public int TicketPurchaseId { get; set; }

    public virtual EventSection EventSection { get; set; }

    public virtual TicketPurchase TicketPurchase { get; set; }
}