// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraphQLserver.Models;

public partial class Venue
{
    public int VenueId { get; set; }

    public string VenueName { get; set; }

    public string VenueType { get; set; }

    public string AdminEmail { get; set; }

    public string AdminPassword { get; set; }

    public string PostalCode { get; set; }

    public string CountryCode { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Country CountryCodeNavigation { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    public virtual ICollection<Section> Sections { get; set; } = new List<Section>();

    public virtual VenueType_ VenueTypeNavigation { get; set; }
}