// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraphQLserver.Models;

public partial class VenueType
{
    public string VenueType1 { get; set; }

    public string VenueTypeName { get; set; }

    public string EventTypeName { get; set; }

    public string EventTypeShortName { get; set; }

    public string EventTypeShortNamePlural { get; set; }

    public string Language { get; set; }

    public virtual ICollection<Venue> Venues { get; set; } = new List<Venue>();
}